# Generated by Django 4.2.7 on 2025-03-20 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='heading', max_length=500)),
                ('welcome', models.CharField(default='welcome', max_length=500)),
                ('description', models.TextField(default='description', max_length=3000)),
                ('special', models.CharField(default='special', max_length=500)),
                ('cool', models.TextField(default='description', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='text1', max_length=500)),
                ('date', models.CharField(default='text2', max_length=500)),
                ('text1', models.TextField(default='text3', max_length=500)),
                ('image', models.ImageField(default='artists.jpg', upload_to='artists')),
            ],
        ),
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='artists', max_length=255)),
                ('name', models.CharField(default='text1', max_length=500)),
                ('image', models.ImageField(default='artistsworks.jpg', upload_to='artistworks')),
                ('price', models.CharField(default='5000', max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='text1', max_length=500)),
                ('address', models.CharField(default='text1', max_length=500)),
                ('phone', models.CharField(default='text1', max_length=500)),
                ('email', models.CharField(default='text1', max_length=500)),
                ('website', models.CharField(default='text1', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('date', models.CharField(default='dd/mm/yyyy', max_length=10)),
                ('time', models.TimeField(default=django.utils.timezone.now, max_length=50)),
                ('event', models.CharField(default='Opening Event', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='exhibitions/')),
                ('date', models.DateField()),
                ('description', models.TextField(default='This is an exhibition', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='text1', max_length=500)),
                ('about', models.CharField(default='text1', max_length=500)),
                ('twitter', models.CharField(max_length=500)),
                ('facebook', models.CharField(max_length=500)),
                ('instagram', models.CharField(max_length=500)),
                ('open_days', models.CharField(default='text1', max_length=500)),
                ('newsletter', models.CharField(default='text1', max_length=500)),
                ('image1', models.ImageField(default='testimony.jpg', upload_to='footer')),
                ('image2', models.ImageField(default='testimony.jpg', upload_to='footer')),
                ('image3', models.ImageField(default='testimony.jpg', upload_to='footer')),
                ('image4', models.ImageField(default='testimony.jpg', upload_to='footer')),
                ('image5', models.ImageField(default='testimony.jpg', upload_to='footer')),
                ('image6', models.ImageField(default='testimony.jpg', upload_to='footer')),
            ],
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='heading', max_length=500)),
                ('description', models.TextField(default='description', max_length=3000)),
                ('background_image1', models.ImageField(default='homepage.jpg', upload_to='homepage')),
            ],
        ),
    ]
