# Generated by Django 4.2.7 on 2025-03-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usanii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morertist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='text1', max_length=500)),
                ('image', models.ImageField(default='moreartist.jpg', upload_to='moreatist')),
                ('title', models.CharField(default='artists', max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
