# Generated by Django 4.2.7 on 2025-03-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usanii', '0002_morertist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Morertist',
            new_name='Moreartist',
        ),
    ]
