# Generated by Django 4.2.7 on 2025-03-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usanii', '0003_rename_morertist_moreartist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='date',
            field=models.CharField(default='Saturday', max_length=200),
        ),
    ]
