# Generated by Django 4.2.7 on 2025-03-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usanii', '0005_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
