# Generated by Django 4.2.7 on 2025-03-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usanii', '0009_alter_customer_event_alter_moreartist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='event',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
