# Generated by Django 4.2.7 on 2025-04-10 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usanii', '0011_alter_customer_date_alter_customer_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='exhibitions/')),
                ('date', models.CharField(default='Saturday', max_length=200)),
                ('description', models.TextField(default='This is an exhibition', max_length=1000)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_capacity', models.PositiveIntegerField(default=50)),
                ('current_attendees', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Exhibitions',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.AddField(
            model_name='booking',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usanii.exhibition'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('email', 'exhibition')},
        ),
    ]
