# Generated by Django 4.2.7 on 2025-04-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usanii', '0012_booking_exhibition_delete_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibition',
            options={'verbose_name': 'Exhibition', 'verbose_name_plural': 'Exhibitions'},
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='end_time',
            field=models.TimeField(help_text='Format: HH:MM (24-hour format), e.g. 21:00 for 9 PM'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='start_time',
            field=models.TimeField(help_text='Format: HH:MM (24-hour format), e.g. 18:00 for 6 PM'),
        ),
    ]
