# Generated by Django 4.2.7 on 2025-05-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usanii', '0013_alter_exhibition_options_alter_exhibition_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworks',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='usanii.artists'),
        ),
    ]
