# Generated by Django 4.2.7 on 2025-05-01 19:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usanii', '0014_artworks_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='exhibition',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exhibition', 'verbose_name_plural': 'Exhibitions'},
        ),
        migrations.AddField(
            model_name='booking',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='usanii.exhibition'),
        ),
    ]
