# Generated by Django 4.2.7 on 2025-05-28 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usanii', '0018_artworks_category_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(default='SIM17484362', max_length=50),
        ),
    ]
